Repository messagerie-melanie2/Roundcube-plugins-Mel, pull requests merged in 2025-09, with the labels that each got.

#318 0009151 - :ambulance: Impossible de cliquer sur "impossible d'utiliser le code ?"
  plugins/mel_doubleauth/mel_doubleauth.php
  plugins/mel_doubleauth/skins/mel_elastic/js_templates/resend.js
Labels: Hotfix

#319 :bookmark: 25.7.1
  plugins/mel_doubleauth/mel_doubleauth.php
  plugins/mel_doubleauth/skins/mel_elastic/js_templates/resend.js
Labels: release

#320 0008859 - ✨Flex Office: Faire en sorte que les ressources affichées puissent avoir le location-on (ville) en mode survol
  plugins/mel_cal_resources/js/lib/resources_functions.js
  plugins/mel_cal_resources/localization/fr_FR.inc
Labels: bug

#323 🐛 Typo dans la conversion d'un id MceToRc #322
  plugins/mel_metapage/js/init/mel_metapage_utils.js
  plugins/mel_metapage/js/init/mel_metapage_utils.min.js
Labels: bug

#325 0008627 - 🐛 - Skin dark: Filtre les boutons supprimer / ajouter et options avancées color est sombre et limite ils sont non visibles
  plugins/roundrive/skins/elastic/style.css
Labels: bug

#331 0009205 - 🐛: Les boutons du calendrier ne sont pas visible en mode Light
  skins/mel_elastic/themes/main/style/calendar.css
  skins/mel_elastic/themes/main/style/less/calendar.less
Labels: bug

#334 typo dans metapage
  plugins/mel_metapage/mel_metapage.php
Labels: style code update

#332 0009211: 🐛 [Mon compte] L'import des membres d'une liste écrase l'existant
  plugins/mel_moncompte/moncompte/Gestionnairelistes.php
Labels: bug

#329 Fix/25.9/0008627/ accessibilite des informations concernant les appareils mobiles
  plugins/mel_moncompte/mobile.js
  plugins/mel_moncompte/skins/mel_elastic/less/mobile.less
  plugins/mel_moncompte/skins/mel_elastic/mobile.css
  plugins/mel_moncompte/statistiques/mobile.php
Labels: bug
