Repository messagerie-melanie2/Roundcube-plugins-Mel, pull requests merged in 2025-08, with the labels that each got.

#302 0009127 - :lipstick: Ajouter le logotype du conseil national de la mer et des littoraux
  plugins/mel_signatures/images/logotype/logo_cnml_v2.gif
  plugins/mel_signatures/images/logotype/logo_cnml_v2.png
Labels: asset

#304 0009122 - :bug: Impossible d'utiliser son code ne marche pas
  plugins/mel/mel.php
  plugins/mel_doubleauth/mel_doubleauth.php
  plugins/mel_doubleauth/skins/mel_elastic/js_templates/da.js
Labels: bug

#303 0008764 - ✨ forcer le refresh quand un article est créé
  plugins/mel_forum/js/lib/forum.js
  plugins/mel_forum/js/lib/refresh.js
  plugins/mel_forum/localization/fr_FR.inc
  plugins/mel_forum/mel_forum.php
  plugins/mel_forum/skins/mel_elastic/less/mel_forum.less
  plugins/mel_forum/skins/mel_elastic/mel_forum.css
  plugins/mel_forum/skins/mel_elastic/templates/forum.html
Labels: enhancement

#306 0008309 - :lipstick: Changement de la couleur de fond pour les switch non sélectionnés
  skins/mel_elastic/themes/classique/style/colors.css
  skins/mel_elastic/themes/classique/style/less/colors.less
  skins/mel_elastic/themes/main/style/colors.css
  skins/mel_elastic/themes/main/style/less/colors.less
  skins/mel_elastic/themes/super-classic/style/colors.css
  skins/mel_elastic/themes/super-classic/style/less/colors.less
Labels: style code update

#307 0008864 - :bug: message du mail d'invit aux espaces
  plugins/mel_workspace/mel_workspace.php
  plugins/mel_workspace/skins/mel_elastic/pictures/logobnum.png
  plugins/mel_workspace/skins/mel_elastic/templates/email.html
Labels: bug

#308 0008633 - :bug: Le menu contextuel de second niveau étiquettes surgit sans être décalé et masque les entrées du premier niveau
  plugins/mel_metapage/js/init/events.js
Labels: bug

#311 recette - 0008633 - :bug: Le sous-menu des labels ne disparaissait pas si on ouvrait un autre sous-menu.
  plugins/mel_metapage/js/init/events.js
Labels: bug

#315 recette - 0009098 - :adhesive_bandage: Plus aucun site ne s'affiche dans le module M'informe
  plugins/mel_news/js/mel_news.js
  plugins/mel_news/js/mel_news.min.js
  plugins/mel_news/mel_news.php
  plugins/mel_news/skins/mel_elastic/templates/news.html
Labels: bug, recette
