Repository messagerie-melanie2/Roundcube-plugins-Mel, pull requests merged in 2025-04, with the labels that each got.

#134 0008895: Script d'import des ressources dans l'annuaire
  plugins/mel_cal_resources/bin/resources_csv.php
Labels: enhancement

#132 0008426 - Fonction [Enregistrer les PJs] amène l'affichage de la fonction [Gérer les etiquettes]
  plugins/mel_metapage/js/lib/metapages_actions/mails/header_manager.js
Labels: bug

#135 recette : Dans certains cas, le changement de frame ne se faisait pas.
  plugins/mel_forum/js/lib/workspace.js
  plugins/mel_workspace/js/lib/program/actions/page.workspace.js
Labels: bug

#137 recette - 0008843 - améliorations des fonctionnements et visuels de module nextcloud
  plugins/mel_nextcloud/js/workspace/module.js
  plugins/mel_workspace/js/lib/WebComponents/workspace_module_block.js
  plugins/mel_workspace/skins/mel_elastic/less/workspace.less
  plugins/mel_workspace/skins/mel_elastic/workspace.css
Labels: bug

#136 recette : Certains éléments de l'espace de travail n'avaient pas le bon visuel
  plugins/mel_nextcloud/skins/elastic/templates/workspace/block.html
  plugins/mel_workspace/js/lib/WebComponents/workspace_module_block.js
Labels: bug

#138 0008847 - Duplication / copier sans participant d'evt privé affiche le cadenas en ouvert et donc en public
  plugins/mel_metapage/js/lib/calendar/event/event_view.js
Labels: bug

#139 0008318 - Chargement qui mouline après export de la liste
  plugins/mel_moncompte/moncompte.js
Labels: bug

#130 0008553 - modification du texte remplacer mel web par bnum
  plugins/mel/localization/en_US.inc
  plugins/mel_doubleauth/localization/fr_FR.inc
  plugins/mel_help/localization/fr_FR.inc
  plugins/rocket_chat/localization/fr_FR.inc
Labels: enhancement

#131 0008134 - Comme dans le courrielleur, permettre de modifier le sujet d'un Mél via l'utilisation de Commentaire
  plugins/mel_metapage/js/init/commands.js
  plugins/mel_metapage/js/init/mel_metapage_utils.js
  plugins/mel_metapage/mel_metapage.php
Labels: enhancement

#143 fix(forum): à l'enregistrement le curseur restait en loading
  plugins/mel_forum/js/lib/create_or_edit_post.js
Labels: bug

#142 retour recette : 0008418: Afficher les numéros de téléphone comme dans Amédée
  plugins/mel/lib/drivers/mce/mce.php
Labels: bug

#145 retour recette 0008724: Impossible d'inviter une personne en @ars.sante.fr
  plugins/mel/lib/drivers/mtes/mtes.php
Labels: bug

#147 recette - 0008901 - F5 ne fonctionnait pas toujours sur un module d'un espace
  plugins/mel_workspace/js/lib/program/actions/page.workspace.js
Labels: bug

#148 recette - 0008898 - certaines fonctionnalités doivent être caché aux externes
  plugins/mel_workspace/js/lib/program/actions/page.workspace.js
  plugins/mel_workspace/mel_workspace.php
Labels: bug

#129 0008547 - Ajouter automatiquement les membres d'un espace a l'événement
  plugins/mel_metapage/js/init/classes/addons/calendar_base.js
  plugins/mel_metapage/js/init/classes/addons/calendar_base.min.js
  plugins/mel_metapage/js/lib/base_mel_object.js
  plugins/mel_metapage/js/lib/calendar/event/event_view.js
  plugins/mel_metapage/js/lib/calendar/event/parts/categoryparts.js
  plugins/mel_metapage/js/lib/calendar/event/parts/guestspart.js
  plugins/mel_workspace/js/lib/program/Parts/agenda.js
  plugins/mel_workspace/js/lib/program/WorkspaceObject.js
  plugins/mel_workspace/js/lib/program/addons/calendar/calendar_additions.js
  plugins/mel_workspace/mel_workspace.php
Labels: enhancement

#150 0008887: Ajouter un 2 logotypes pour label égalité et label diversité
  plugins/mel_signatures/images/logotype/labels-E-D-2.gif
  plugins/mel_signatures/images/logotype/labels-E-D-2.png
Labels: enhancement

#149 0008902 - Ajout des classes pour les éléments déjà existant pour la refonte des thèmes
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/FormComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/IconComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/LoadingComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/RoundShapeComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/constants.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/dropdown/HTMLDropDownElement.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/dropdown/RoundShapeComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/dropdown/VariationComponent.js
Labels: enhancement

#141 0008861 - mobile et pc fenetre nav reduite la toolbar icones non visibles
  skins/mel_elastic/themes/main/style/less/taskbar.less
  skins/mel_elastic/themes/main/style/taskbar.css
Labels: bug

#152 0008903 - La tooltip des priorités de filtrage rapide était illisible
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: bug

#153 recette - 0008842 - Masquer la barre de gauche lorsque l'on ouvre Tchap dans un espace
  plugins/tchap/tchap.js
Labels: bug

#154 recette - 0008844 - Cacher la barre du haut pour ne pas pouvoir quitter l'espace ne fonctionnait pas à chaque fois
  plugins/mel_wekan/js/workspace/workspace_additions.js
Labels: bug

#156 25.3 - Documentation du fichier `Workspace.php`
  plugins/mel_workspace/lib/Workspace.php
  plugins/mel_workspace/mel_workspace.php
Labels: documentation

#155 recette - 0008909 - Le bouton "Voir tout" dans mes documents ouvre nextcloud
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/HTMLBnumButton.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/js_html_base_web_elements.js
  plugins/mel_nextcloud/js/workspace/module.js
  plugins/mel_nextcloud/localization/fr_FR.inc
  plugins/mel_nextcloud/localization/global/fr_FR.inc
  plugins/mel_nextcloud/mel_nextcloud.php
  plugins/mel_nextcloud/skins/elastic/templates/workspace/block.html
  plugins/mel_workspace/js/lib/WebComponents/workspace_module_block.js
  plugins/mel_workspace/localization/fr_FR.inc
Labels: bug, enhancement

#157 0008913 - :sparkles: Ajout de `getLocalization`
  plugins/mel_metapage/js/lib/base_mel_object.js
Labels: enhancement

#158 0008912 - :recycle: Documentation et refactor des fichiers planning et agenda
  plugins/mel_workspace/js/lib/program/Parts/agenda.js
  plugins/mel_workspace/js/lib/program/Parts/planning.js
  plugins/mel_workspace/js/lib/program/WorkspaceObject.js
Labels: refactor, documentation

#160 0008906 - :bug: Faire en sorte que le titre affiché pour tous les modules reprend bien espace de travail
  plugins/mel_workspace/js/lib/program/actions/page.workspace.js
  plugins/mel_workspace/js/lib/program/navbar.generator.js
  plugins/mel_workspace/localization/workspace/fr_FR.inc
  plugins/mel_workspace/mel_workspace.php
Labels: bug

#162 0008915 - :bug: Corrections d'élements pas encore utilisé
  plugins/mel_metapage/js/lib/base_mel_object.js
  plugins/mel_metapage/js/lib/classes/frame_manager.js
Labels: bug

#163 0008916 - :memo: :coffin: Suppression du code inutile dans commands.js + documentation
  plugins/mel_metapage/js/init/commands.js
Labels: style code update, documentation

#165 prettier - 🎨 📝 Application de prettier sur les fichiers relatifs aux notes + documentation
  plugins/mel_metapage/js/lib/metapages_actions/notes.js
  plugins/mel_metapage/js/lib/metapages_actions/notes/pined_sticker.js
  plugins/mel_metapage/js/lib/metapages_actions/notes/sticker.js
Labels: style code update, documentation

#170 recette - prettier - 0008903 :art: Application de prettier sur color.less et mail.less
  skins/mel_elastic/themes/main/style/less/colors.less
  skins/mel_elastic/themes/main/style/less/mails.less
Labels: style code update

#171 recette - 0008903 - :bug: La tooltip des priorités de filtrage rapide était illisible
  skins/mel_elastic/themes/main/style/colors.css
  skins/mel_elastic/themes/main/style/dark-colors.css
  skins/mel_elastic/themes/main/style/less/colors.less
  skins/mel_elastic/themes/main/style/less/dark-colors.less
  skins/mel_elastic/themes/main/style/less/mails.less
  skins/mel_elastic/themes/main/style/mails.css
Labels: bug

#173 fix(annuaire) : Correctif pour que ça ne s'applique qu'aux modales
  plugins/mel_metapage/skins/mel_elastic/annuaire_part.css
  plugins/mel_metapage/skins/mel_elastic/less/annuaire_part.less
Labels: bug

#164 0008908 - 🐛 Rafraichir la page en cours fait disparaitre la page du bord de l'edt et remet la page global de tous les bord
  plugins/mel_metapage/js/lib/classes/frame_manager.js
  plugins/mel_workspace/js/lib/WebComponents/NavbarComponents/nav.js
  plugins/mel_workspace/js/lib/WebComponents/navbar.js
  plugins/mel_workspace/js/lib/program/actions/page.workspace.js
  plugins/mel_workspace/js/lib/program/navbar.generator.js
Labels: bug

#174 0008927 - 🏗 Ajouter automatiquement les webcomposants
  plugins/bnum/bnum_plugin.php
  plugins/mel_elastic/mel_elastic.php
  plugins/mel_elastic/program/webcomponents.php
  plugins/mel_forum/mel_forum.php
  plugins/mel_helper/lib/mel_linq.php
  plugins/mel_metapage/mel_metapage.php
  plugins/mel_workspace/mel_workspace.php
  skins/mel_elastic/templates/includes/layout.html
Labels: enhancement, refactor

#178 0008696 - :sparkles: Valeurs par défaut pour la recherche dans les courriels
  plugins/bnum_mail/bnum_mail.php
  plugins/bnum_mail/config.inc.php.dist
  skins/mel_elastic/styles/less/mails.less
  skins/mel_elastic/styles/mails.css
  skins/mel_elastic/templates/mail.html
Labels: enhancement

#169 0007634 - contact annuaire ajouter un champ pour affichage des autres emails
  plugins/mel/lib/drivers/mtes/mtes.php
  plugins/mel_contacts/lib/mel_contacts_mapping.php
  plugins/mel_contacts/localization/fr_FR.inc
  plugins/mel_contacts/mel_contacts.php
Labels: enhancement

#180 0008830 - ajouter les destinataires au message d alerte de grillage de compte
  plugins/mel_massmail/config.inc.php.dist
  plugins/mel_massmail/mel_massmail.php
Labels: enhancement

#179 :sparkles: Création du webcomponents `bnum-helper`.
  plugins/mel_elastic/js/lib/webcomponents/HTMLBnumHelperElement.js
  plugins/mel_elastic/program/webcomponents.php
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/js_html_base_web_elements.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/lib/AHTMLCustomInternalElement.js
  skins/mel_elastic/styles/less/mixins/mixins.less
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: enhancement

#182 0008932: impossible de télécharger un article
  plugins/mel_forum/js/lib/manager.js
Labels: bug

#181 [HOTFIX] 0008932: impossible de télécharger un article
  plugins/mel_forum/js/lib/manager.js
Labels: bug

#183 0008904 - Modale de recherche d'un membre depuis l'annuaire : Non responsive lorsqu'on utilise le bouton Inviter un membre
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: bug

#185 0008854 - Articles: Ajouter pop-up pour indiquer la prise en compte du choix de notif ou pas sur le salon tchap
  plugins/mel_forum/js/lib/workspace.js
  plugins/mel_workspace/localization/workspace/fr_FR.inc
  plugins/mel_workspace/skins/mel_elastic/templates/params.html
Labels: enhancement

#186 0008934 - 🚑 Attendre que tchap soit chargé avant d'activer les fonctionnalités tchap
  plugins/tchap/tchap.js
Labels: bug

#187 0008934 - 🐛 Attendre que tchap soit chargé avant d'activer les fonctionnalités tchap
  plugins/tchap/tchap.js
Labels: bug

#189 0008342 - :bug: Erreur si l'on clique deux fois sur enregistrer dans le gestionnaire d'absence
  plugins/mel_moncompte/moncompte/Gestionnaireabsence.php
Labels: bug

#176 0008930 - probleme double clics pour ouvrir une fiche contact
  plugins/annuaire/annuaire.js
Labels: enhancement

#190 0008938 - :bug: Le bouton 'Revenir à' ne fonctionne pas
  plugins/mel_metapage/js/lib/classes/frame_manager.js
  plugins/mel_workspace/js/lib/program/actions/page.workspace.js
Labels: bug

#191 recette - 0008134 - :safety_vest: Les accents et caractères spéciaux ne fonctionnaient pas lors de la modification du sujet d'un mail
  plugins/mel_metapage/mel_metapage.php
Labels: bug

#192 0008942 - :bug: Si la configuration du dossier des éléments envoyés est `---`
  plugins/mel/mel.js
Labels: bug

#193 0008943 - ✨ Ajout de du logo de l'arche sur la page de login.
  .vscode/bnum-image.code-snippets
  plugins/mel_elastic/js/lib/webcomponents/HTMLColorModePicture.js
  plugins/mel_elastic/program/webcomponents.php
  plugins/mel_metapage/js/lib/constants/regexp.js
  skins/mel_elastic/images/arche-logo-dark.svg
  skins/mel_elastic/images/arche-logo-light.svg
  skins/mel_elastic/styles/less/login.less
  skins/mel_elastic/styles/login.css
  skins/mel_elastic/templates/login.html
Labels: enhancement

#194 prettier - :art: Application de prettier php sur mel_workspace et mel_wekan
  plugins/mel_wekan/mel_wekan.php
  plugins/mel_workspace/mel_workspace.php
Labels: style code update

#195 0008944 - 🐛 Le module tâche n'ajoute pas les utilisateurs à la création.
  plugins/mel_workspace/mel_workspace.php
Labels: bug

#196 🐛 0008811: Logo Bnum manquant : le mail contenant le code ne contient plus le logo <image manquante>
  plugins/mel_doubleauth/mel_doubleauth.php
Labels: bug

#197 0008943 - :rewind: Suppression de du logo de l'arche
  skins/mel_elastic/images/arche-logo-dark.svg
  skins/mel_elastic/images/arche-logo-light.svg
  skins/mel_elastic/templates/login.html
Labels: other
