Repository messagerie-melanie2/Roundcube-plugins-Mel, pull requests merged in 2025-07, with the labels that each got.

#269 0008953 - :bricks: Utilisation du proto-design system bnum
  plugins/mel_suspects_urls/js/mel_suspects_urls.js
  plugins/mel_suspects_urls/skins/mel_elastic/templates/suspectsurls_settings.html
Labels: enhancement, refactor

#268 0009087 - :sparkles: Dans la popup de ressources faire le lien entre utilisateur et ville via le code postal
  plugins/mel_cal_resources/js/add_resources.js
  plugins/mel_cal_resources/js/lib/filter_base.js
  plugins/mel_cal_resources/js/lib/utils.js
  plugins/mel_cal_resources/lib/Locality.php
  plugins/mel_cal_resources/mel_cal_resources.php
Labels: enhancement

#271 #270 - :sparkles: Ajouter des fonctions utiles à `bnum_plugin`
  plugins/bnum/bnum_plugin.php
Labels: enhancement

#267 0008953 - ✨Plugin des URLs Suspectes
  plugins/mel_metapage/mel_metapage.php
  plugins/mel_suspects_urls/js/mel_suspects_urls.js
  plugins/mel_suspects_urls/localization/fr_FR.inc
  plugins/mel_suspects_urls/mel_suspects_urls.php
  plugins/mel_suspects_urls/skins/mel_elastic/less/suspects_urls.less
  plugins/mel_suspects_urls/skins/mel_elastic/suspects_urls.css
  plugins/mel_suspects_urls/skins/mel_elastic/templates/suspectsurls_settings.html
Labels: enhancement

#277 recette - 0008421 - :bug: augmenter le nombre de ligne par case dans l'affichage au mois dans Calendrier
  plugins/bnum_agenda/bnum_agenda.php
Labels: bug

#278 0009111 - 🚑 Participants indésirables lors de la convertion mail -> évènement
  .github/workflows/ci.yml
  plugins/mel_metapage/localization/fr_FR.inc
  plugins/mel_metapage/skins/mel_elastic/templates/event_modal.html
Labels: bug, text update, refactor

#280 0008697 - 💄 - Changer la couleur de la pastille jaune pour statut peut-être
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: asset

#284 recette - #283 - 🚑 Les notifications plantent si un utilisateur n'existe pas.
  plugins/mel_notification/mel_notification.php
Labels: bug

#291 :ambulance: Ajout d'un système de mapping pour `getRoutage` de mtes
  plugins/mel/config.inc.php.dist
  plugins/mel/lib/drivers/mtes/mtes.php
Labels: bug, enhancement

#293 0008734 - ♿️ Les boutons fermer et réduire modale mail n'ont pas de title ni de description au survol
  plugins/mel_metapage/js/init/classes/misc/wl_popup.js
  plugins/mel_metapage/localization/fr_FR.inc
Labels: enhancement

#295 0009039 - :bug: Superposition du titre des liens utiles avec le bouton "Ajouter"
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/HTMLBnumButton.js
  plugins/mel_useful_link/js/lib/manager.js
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: bug
