Repository messagerie-melanie2/Roundcube-plugins-Mel, pull requests merged in 2025-02, with the labels that each got.

#22 fix(wsp): Les notifications ne fonctionnaient pas lorsqu'on ajoutait un utilisateur
  plugins/mel_workspace/mel_workspace.php
Labels: bug

#23 fix(workspace): dans les paramètres d'un espace, au rechargement, on revient sur les pages des paramètres
  plugins/mel_workspace/js/params.js
Labels: bug

#24 refactor(jshtml): Refactor pour eviter les erreurs
  plugins/mel_metapage/js/lib/html/JsHtml/ABaseModulesJsHtml.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/bootstrap-loader.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsAccessibilityHtml.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsBootstrapHtml.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsCustomHtml.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsHtml.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsInputsHtml.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsMelHtml.js
  plugins/mel_metapage/js/lib/html/JsHtml/MelHtml.js
Labels: enhancement

#27 fix(frames): Les frames étaient parfois cachés
  plugins/mel_metapage/js/lib/classes/frame_manager.js
  plugins/mel_nextcloud/nextcloud.js
Labels: bug

#28 Feature/25.2/0008760/refactorisation header json
  plugins/mel_forum/mel_forum.php
  plugins/mel_metapage/bnum_plugin.php
  plugins/mel_workspace/mel_workspace.php
Labels: enhancement

#31 0008732: Cliquer sur un document ne l'ouvre pas dans nextcloud
  plugins/mel_nextcloud/js/workspace/module.js
Labels: bug

#35 fix(double_auth) : Affichage de la modale si double auth non forcé
  plugins/mel_doubleauth/mel_doubleauth.php
Labels: bug

#36 Hotfix récupération jenkins pour les balp
  plugins/mel/lib/drivers/mce/mce.php
Labels: bug

#37 feat(forum) : Notification des utilisateurs du Workspace
  plugins/mel_forum/localization/fr_FR.inc
  plugins/mel_forum/mel_forum.php
Labels: enhancement

#40 fix(rcs): Afficher plus d'information faire des créneaux de 1h
  plugins/mel_cal_resources/js/lib/resource_base.js
Labels: bug

#42 Feature/25.2/0008463 rcs accessibility
  plugins/mel_cal_resources/js/lib/resource_base.js
  plugins/mel_cal_resources/js/lib/resource_location.js
  plugins/mel_cal_resources/skins/mel_elastic/js_template/resource_location.js
Labels: bug, enhancement

#43 feat(notes): Demander confirmation avant de supprimer une note
  plugins/mel_metapage/js/lib/html/JsHtml/JsHtml.js
  plugins/mel_metapage/js/lib/metapages_actions/notes/sticker.js
  plugins/mel_metapage/localization/fr_FR.inc
Labels: bug, enhancement

#46 0008754: Ne pas ajouter le suffix -1 sur le nom du groupe si le nom …
  plugins/mel_workspace/lib/Workspace.php
Labels: bug

#47 feat(app): Pouvoir cacher le footer sur certaines pages
  plugins/mel_elastic/mel_elastic.php
  plugins/mel_metapage/bnum_plugin.php
  plugins/mel_wekan/mel_wekan.php
  plugins/mel_workspace/mel_workspace.php
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
  skins/mel_elastic/ui.js
Labels: bug, enhancement

#53 perf(forum): déplacement de la vérifcation de droit
  plugins/mel_forum/mel_forum.php
Labels: enhancement

#50 Feature/25.2/8778-notif-tchap
  plugins/mel_forum/js/lib/workspace.js
  plugins/mel_forum/localization/fr_FR.inc
  plugins/mel_forum/mel_forum.php
  plugins/mel_workspace/js/lib/connectors.js
  plugins/mel_workspace/js/lib/program/WorkspaceObject.js
  plugins/mel_workspace/mel_workspace.php
  plugins/mel_workspace/skins/mel_elastic/templates/params.html
  plugins/tchap/tchap.php
Labels: enhancement

#45 feat(forum) : Mise en place du loader sur curseur
  plugins/mel_forum/js/lib/comments.js
  plugins/mel_forum/js/lib/create_or_edit_post.js
  plugins/mel_forum/js/lib/forum.js
  plugins/mel_forum/js/lib/manager.js
  plugins/mel_metapage/js/lib/helpers/cursorUtils.js
Labels: enhancement

#56 feat(moncompte) : 0008237: Afficher pour chaque filtre - Activé ou pas - comme pour les jeux de filtres
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: bug

#52 fix(rcs): Décalage dans l'affichage des salles et des disponibilités si on a beaucoup de ressources listées
  plugins/mel_cal_resources/js/lib/resources_functions.js
Labels: bug

#51 feat(rcs): Ressources : faire en sorte que fullcalendar n'affiche qu'un créneau horaire et pas 24h
  plugins/mel_cal_resources/js/lib/resource_base.js
  plugins/mel_cal_resources/js/lib/resources_functions.js
  plugins/mel_cal_resources/skins/mel_elastic/js_template/resource.js
Labels: bug

#60 fix(metrics): Les metrics envoyés régulièrement envoyaient `undefined`
  plugins/mel_metapage/js/lib/mel_object.js
  plugins/mel_metapage/js/lib/metapages_actions/bnum/main_nav_metrics.js
Labels: bug

#58 refactor(rcs): Améliorer la fonction resource_render
  plugins/mel_cal_resources/js/lib/resources_functions.js
  plugins/mel_cal_resources/js/lib/webcomponents/HTMLResourceElement.js
  plugins/mel_cal_resources/skins/mel_elastic/js_template/resource.js
  plugins/mel_cal_resources/skins/mel_elastic/less/style.less
  plugins/mel_cal_resources/skins/mel_elastic/style.css
  plugins/mel_metapage/js/lib/classes/modal.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/AHTMLCustomTemplateElement.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsHtml.js
Labels: enhancement

#48 feat(rcs): Implémenter la gestion des agendas de ressources intégrée au Bnum
  plugins/mel_cal_resources/config.inc.php.dist
  plugins/mel_cal_resources/js/add_resources.js
  plugins/mel_cal_resources/js/lib/filter_base.js
  plugins/mel_cal_resources/js/lib/resource_base.js
  plugins/mel_cal_resources/js/lib/resource_location.js
  plugins/mel_cal_resources/js/lib/webcomponents/HTMLTabSelectElement.js
  plugins/mel_cal_resources/localization/fr_FR.inc
  plugins/mel_cal_resources/mel_cal_resources.php
  plugins/mel_cal_resources/skins/mel_elastic/less/style.less
  plugins/mel_cal_resources/skins/mel_elastic/style.css
  plugins/mel_metapage/js/lib/calendar/event/parts/location_part.js
  plugins/mel_metapage/js/lib/classes/DialogMultiPage.js
  plugins/mel_metapage/js/lib/classes/modal.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/tab_web_element.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/tabs/HTMLTabContainerAndReceiver.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/tabs/HTMLTabElement.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsCustomHtml.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsHtml.js
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: enhancement

#61 feat(rcs): Agrandir la taille de la modale
  plugins/mel_cal_resources/js/add_resources.js
  plugins/mel_cal_resources/js/lib/resource_base.js
  plugins/mel_cal_resources/js/waiting_events.js
  plugins/mel_cal_resources/skins/mel_elastic/js_template/resource.js
  plugins/mel_cal_resources/skins/mel_elastic/less/style.less
  plugins/mel_cal_resources/skins/mel_elastic/style.css
  skins/mel_elastic/styles/less/style.less
Labels: bug, enhancement

#64 fix: Freebusy creator name + add uid
  plugins/calendar/calendar.php
  plugins/calendar/drivers/mel/mel_driver.php
Labels: bug

#62 fix(externals): ne devraient pas apparaitre pour un externe
  plugins/mel_external_users/externals.css
  plugins/mel_metapage/mel_metapage.php
Labels: bug

#65 feat(rcs): Flex office-mettre le nom de la personne qui réserve plutôt que le libellé "occupé"
  plugins/mel_cal_resources/js/lib/resources_functions.js
  plugins/mel_cal_resources/localization/fr_FR.inc
  plugins/mel_metapage/js/lib/calendar/event/parts/guestspart.free_busy.js
  plugins/mel_metapage/js/lib/calendar/free_busy_loader.js
Labels: enhancement

#68 fix(frames): Prendre en compte les "#" dans les liens passés dans les notifications
  plugins/mel_metapage/js/init/classes/misc/frame_manager_no_module.js
  plugins/mel_metapage/js/init/events.js
  plugins/mel_metapage/js/lib/classes/frame_manager.js
Labels: bug, enhancement

#67 feat(rcs): Flex office/Ressource ne pas pouvoir réserver une ressource deux fois sur le même créneau
  plugins/mel_cal_resources/js/lib/resource_base.js
  plugins/mel_cal_resources/js/lib/resources_functions.js
Labels: bug

#70 fix(edt) : 0008753: La désaccentuation du nom des espaces n'est pas parfaite
  plugins/mel_workspace/lib/Workspace.php
Labels: bug

#71 fix(rcs): Automatiquement séléctionner le lieu
  plugins/mel_cal_resources/js/add_resources.js
  plugins/mel_cal_resources/js/lib/filter_base.js
  plugins/mel_cal_resources/js/lib/utils.js
  plugins/mel_cal_resources/lib/Locality.php
  plugins/mel_cal_resources/mel_cal_resources.php
Labels: bug

#73 feat(useful_links) : 0008599: Ajout de liens utiles dans la bibliothèque
  plugins/mel_useful_link/icon/organisation/demarches-simplifiees.png
  plugins/mel_useful_link/icon/organisation/resana.png
Labels: enhancement

#76 fix(wsp): typo quand on rejoint un espace public
  plugins/mel_workspace/js/lib/program/actions/page.not_in_workspace.js
  plugins/mel_workspace/localization/workspace/fr_FR.inc
Labels: text update

#74 fix(Forum) : Gestion des droits utilisateurs
  plugins/mel_forum/mel_forum.php
Labels: bug

#77 feat(forum) afficher les noms des personnes qui ont réagit
  plugins/mel_forum/js/lib/comments.js
  plugins/mel_forum/js/lib/forum.js
  plugins/mel_forum/js/lib/manager.js
  plugins/mel_forum/localization/fr_FR.inc
  plugins/mel_forum/mel_forum.php
  plugins/mel_forum/skins/mel_elastic/templates/forum.html
Labels: enhancement

#79 fix(moncompte) : 0008399: Mode dark: Modifier la couleur du fond dans gestionnaire de liste lorsqu'on recherche un agent dans l'annuaire
  plugins/annuaire/skins/mel_elastic/annuaire.css
  plugins/mel_moncompte/skins/mel_elastic/templates/listes.html
  skins/mel_elastic/themes/main/style/less/theme.less
  skins/mel_elastic/themes/main/style/theme.css
Labels: bug

#80 hotfix(forum) problème dans les appels ajax
  plugins/mel_forum/js/lib/create_or_edit_post.js
Labels: bug

#78 feat(contact) : 0008418: Afficher les numéros de téléphone comme dans Amédée
  plugins/mel/lib/drivers/mce/mce.php
  plugins/mel/lib/drivers/mtes/mtes.php
Labels: enhancement

#81 hotfix(forum) modification du fonctionnement du chargement des images
  plugins/mel_forum/mel_forum.php
Labels: bug
