Repository messagerie-melanie2/Roundcube-plugins-Mel, pull requests merged in 2025-06, with the labels that each got.

#229 0008564 - :speech_balloon: Faute lorsque le champs "Ajouter une audioconférence" est vide.
  plugins/mel_metapage/localization/fr_FR.inc
Labels: text update

#233 0008968 - :bug: Décalage dans l'affichage des plannings de moins d'une heure et non prise en compte des evts de l'agenda
  plugins/mel_workspace/js/lib/WebComponents/planning.js
Labels: bug

#231 recette - 0008404 - Correction du code pour affichage dynamique des valeurs concernant l'afficha de la liste des mobiles
  plugins/mel_moncompte/mobile.js
  plugins/mel_moncompte/statistiques/mobile.php
Labels: bug

#238 0009017 - :bug: Désactiver favikontoolkit
  plugins/mel_useful_link/js/lib/mel_link.js
Labels: bug

#235 recette - 0008403 - Correction du code pour affichage correcte des title des boutons resync et suppression mobile
  plugins/mel_labels_sync/localization/fr_FR.inc
  plugins/mel_labels_sync/mel_labels_sync.php
  plugins/mel_moncompte/statistiques/mobile.php
Labels: bug

#240 recette - 0009049 - :bug: La modale pour changer de kanban ne fonctionne pas
  plugins/mel_wekan/mel_wekan.php
Labels: bug

#242 0009051 - :bug: Parfois, la barre de navigation d'un espace ne s'affiche pas
  plugins/mel_workspace/js/lib/WebComponents/NavbarComponents/button.js
  plugins/mel_workspace/js/lib/WebComponents/NavbarComponents/components.js
  plugins/mel_workspace/js/lib/WebComponents/NavbarComponents/nav.js
  plugins/mel_workspace/js/lib/WebComponents/navbar.js
Labels: bug, documentation

#243 recette - 0008404 - 🐛 Correction erreur de syntaxe + accessibilité des boutons
  plugins/mel_moncompte/mobile.js
Labels: bug

#247 0008410 - :sparkles: Ajouter des fonctionnalités aux notes
  plugins/mel_metapage/js/lib/metapages_actions/notes/sticker.js
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: enhancement

#250 0009030 - :bug: Ne pas importer les comptes avec une adresse email `null`.
  plugins/mel_workspace/lib/Workspace.php
Labels: bug

#251 0008427 - :lipstick: [Enregistrer dans le Stockage] Fonction [Créer un dossier] ne se voit pas
  plugins/roundrive/roundrive.js
  plugins/roundrive/skins/elastic/style.css
  plugins/roundrive/skins/elastic/templates/message_plugin.html
Labels: bug

#254 #253 - :ambulance: Les liens utiles ne fonctionnent plus
  plugins/mel_useful_link/js/lib/mel_link.js
Labels: bug

#257 0009050 - :bug: Impossible d'ouvrir les liens pour les mails ouvert dans une fenêtre externe.
  plugins/bnum_mail/bnum_mail.php
  plugins/mel_metapage/js/init/events.js
Labels: bug

#260 0008421 - ✨ - Augmenter le nombre de ligne par case dans l'affichage au mois dans Calendrier
  plugins/bnum_agenda/bnum_agenda.php
  plugins/bnum_agenda/config.inc.php.dist
  plugins/bnum_agenda/localization/fr_FR.inc
  plugins/calendar/calendar_ui.js
  plugins/calendar/localization/fr_FR.inc
  plugins/mel_metapage/js/functions.js
  plugins/mel_metapage/js/init/events.js
  plugins/mel_metapage/skins/mel_elastic/templates/options/calendar.html
Labels: enhancement
