Repository messagerie-melanie2/Roundcube-plugins-Mel, pull requests merged in 2025-03, with the labels that each got.

#83 style(forum): eslint
  plugins/mel_forum/js/lib/access_error.js
  plugins/mel_forum/js/lib/comments.js
  plugins/mel_forum/js/lib/create_or_edit_post.js
  plugins/mel_forum/js/lib/forum.js
  plugins/mel_forum/js/lib/manager.js
  plugins/mel_forum/js/lib/workspace.js
Labels: style code update

#85 core(app): Merge 25.2 into 25.3
  plugins/calendar/calendar.php
  plugins/calendar/drivers/mel/mel_driver.php
  plugins/mel_cal_resources/config.inc.php.dist
  plugins/mel_cal_resources/js/add_resources.js
  plugins/mel_cal_resources/js/lib/favorite_loader.js
  plugins/mel_cal_resources/js/lib/filter_base.js
  plugins/mel_cal_resources/js/lib/resource_base.js
  plugins/mel_cal_resources/js/lib/resources_functions.js
  plugins/mel_cal_resources/js/lib/utils.js
  plugins/mel_cal_resources/lib/Locality.php
  plugins/mel_cal_resources/localization/fr_FR.inc
  plugins/mel_cal_resources/mel_cal_resources.php
  plugins/mel_external_users/externals.css
  plugins/mel_forum/js/lib/comments.js
  plugins/mel_forum/js/lib/create_or_edit_post.js
  plugins/mel_forum/js/lib/forum.js
  plugins/mel_forum/js/lib/manager.js
  plugins/mel_forum/localization/fr_FR.inc
  plugins/mel_forum/mel_forum.php
  plugins/mel_forum/skins/mel_elastic/templates/forum.html
  plugins/mel_metapage/js/init/classes/misc/frame_manager_no_module.js
  plugins/mel_metapage/js/init/classes/misc/helper.js
  plugins/mel_metapage/js/init/events.js
  plugins/mel_metapage/js/lib/calendar/event/parts/guestspart.free_busy.js
  plugins/mel_metapage/js/lib/calendar/free_busy_loader.js
  plugins/mel_metapage/js/lib/classes/frame_manager.js
  plugins/mel_metapage/mel_metapage.php
  plugins/mel_workspace/js/lib/program/actions/page.not_in_workspace.js
  plugins/mel_workspace/lib/Workspace.php
  plugins/mel_workspace/localization/workspace/fr_FR.inc
Labels: refactor

#84 fix(mail): Il y avait certaines erreurs lié au jshtml dans le mail
  plugins/mel_metapage/js/init/classes/misc/helper.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsHtml.js
  plugins/mel_metapage/js/lib/metapages_actions/mails/favorite_folder.js
  plugins/mel_metapage/js/lib/metapages_actions/mails/folder_color.js
Labels: bug

#86 fix(tasks): Créer une tâche depuis le bouton créer ne fonctionnait plus
  plugins/mel_metapage/js/functions.js
Labels: bug

#91 fix(double_auth) : 0008793: Modifier la phrase modale double auth
  plugins/mel_metapage/localization/fr_FR.inc
Labels: text update

#92 feat(calendar): droit prive ajouter lecture
  plugins/mel_moncompte/ressources/calendar.php
Labels: enhancement

#95 feat(webcomponents): Amélioration les boutons du bnum
  plugins/mel_metapage/js/actions/test.js
  plugins/mel_metapage/js/lib/constants/constants.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/HTMLMelButton.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/bootstrap-loader.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/ButtonCreator.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/FormComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/HTMLBnumButton.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/IconComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/LoadingComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/RoundShapeComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/constants.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/js_html_base_web_elements.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/lib/AHTMLComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/lib/AHTMLCustomInternalElement.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/wrapper.js
  plugins/mel_metapage/skins/mel_elastic/templates/test.html
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: enhancement

#94 fix(wsp): Correction de la faute d'orthographe dans la fenêtre ajout des membres
  plugins/mel_metapage/js/functions.js
  plugins/mel_metapage/localization/fr_FR.inc
  plugins/mel_workspace/js/params.js
  plugins/mel_workspace/localization/workspace/fr_FR.inc
Labels: text update, refactor

#99 feat(forum) : modification et accessibilité du bouton retour de la mo…
  plugins/mel_metapage/js/functions.js
  plugins/mel_metapage/localization/fr_FR.inc
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
Labels: enhancement

#100 Hotfix/25.3/oublie refonte workspace
  plugins/mel_metapage/js/functions.js
  plugins/tchap/tchap.php
Labels: bug

#98 Feat(forum) : Format d'affichage de la date pour les articles
  plugins/mel_forum/js/lib/comments.js
  plugins/mel_forum/js/lib/forum.js
  plugins/mel_forum/js/lib/front_page_post.js
  plugins/mel_forum/js/lib/new_posts.js
  plugins/mel_forum/js/lib/utils.js
  plugins/mel_forum/localization/fr_FR.inc
  plugins/mel_forum/mel_forum.php
  plugins/mel_forum/skins/mel_elastic/templates/forum.html
  plugins/mel_forum/skins/mel_elastic/templates/front-page-post.html
  plugins/mel_forum/skins/mel_elastic/templates/new-posts.html
Labels: enhancement

#96 feat(wsp): Retirer bouton pour agrandir description
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/ButtonCreator.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/HTMLBnumButton.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/button/LoadingComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/input_file.js
  plugins/mel_workspace/js/lib/WebComponents/NavbarComponents/components.js
  plugins/mel_workspace/localization/fr_FR.inc
  plugins/mel_workspace/skins/mel_elastic/less/navbar.less
  plugins/mel_workspace/skins/mel_elastic/navbar.css
Labels: enhancement, documentation

#101 fix(webcomponents): Parfois, les favoris ont des erreurs et ne peuvent pas être chargés
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/js_html_base_web_elements.js
  plugins/mel_metapage/js/lib/html/JsHtml/JsCustomHtml.js
Labels: bug

#89 Feat/25.3/0007659-ajout-bouton-mail
  plugins/annuaire/annuaire.js
  plugins/annuaire/annuaire.php
  plugins/mel_elastic/mel_elastic.php
  plugins/mel_metapage/bnum_plugin.php
  plugins/mel_metapage/js/init/commands.js
  plugins/mel_metapage/js/init/events.js
  plugins/mel_metapage/js/lib/constants/regexp.js
  plugins/mel_metapage/localization/fr_FR.inc
  skins/mel_elastic/elastic_ui.js
  skins/mel_elastic/styles/mails.css
  skins/mel_elastic/templates/message.html
Labels: enhancement

#106 feat(wsp)cacher la barre de gauche de tchap
  plugins/tchap/tchap.js
Labels: enhancement

#110 0008882: L'horaire du planning est basé sur les working hour
  plugins/mel_workspace/js/lib/WebComponents/fullcalendar.js
Labels: enhancement

#112 0008841-agenda
  skins/mel_elastic/styles/calendar.css
  skins/mel_elastic/styles/less/calendar.less
Labels: enhancement

#113 0008861 - Mobile et PC fenêtre nav reduite : La toolbar en theme par défaut et classique mode clair n'affiche pas les icones
  skins/mel_elastic/themes/main/style/less/theme.less
  skins/mel_elastic/themes/main/style/theme.css
Labels: bug

#115 0008884 - Les personnes notifiés par mail n'étaient pas ajouter au ldap lors de l'ajout à l'espace
  plugins/mel_workspace/lib/WspMailBody.php
  plugins/mel_workspace/mel_workspace.php
Labels: bug

#116 0008808: Les log de type ::setAcl ne donne pas le droit positionné
  plugins/mel_moncompte/ressources/calendar.php
  plugins/mel_moncompte/ressources/contacts.php
  plugins/mel_moncompte/ressources/mailbox.php
  plugins/mel_moncompte/ressources/tasks.php
Labels: other

#118 0008888: Ajouter des snippets pour vscode
  .vscode/bnum-dropdown.code-snippets
  .vscode/custom-components.code-snippets
  .vscode/roundcube-html.code-snippets
  .vscode/templates.code-snippets
  .vscode/webcomponent-workspace.code-snippets
Labels: style code update

#117 0008843: Documents
  plugins/mel_metapage/js/actions/test.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/AHTMLCustomTemplateElement.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/dropdown/HTMLDropDownElement.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/dropdown/HtmlDropDownOptions.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/dropdown/RoundShapeComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/dropdown/VariationComponent.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/js_html_base_web_elements.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/lib/AHTMLComponent.js
  plugins/mel_metapage/skins/mel_elastic/templates/test.html
  plugins/mel_nextcloud/js/workspace/module.js
  plugins/mel_nextcloud/mel_nextcloud.php
  plugins/mel_nextcloud/skins/elastic/templates/workspace/block.html
  plugins/mel_workspace/js/lib/WebComponents/workspace_module_block.js
  plugins/mel_workspace/skins/mel_elastic/less/workspace.less
  plugins/mel_workspace/skins/mel_elastic/workspace.css
  plugins/roundrive/lib/BnumClient.php
  plugins/roundrive/lib/BnumFileSystem.php
  plugins/roundrive/lib/BnumWebDavAdaptater.php
  plugins/roundrive/lib/roundrive_files_engine.php
  plugins/roundrive/roundrive.php
  plugins/roundrive/roundrive_module.js
  skins/mel_elastic/styles/less/style.less
  skins/mel_elastic/styles/style.css
  skins/mel_elastic/themes/main/style/colors.css
  skins/mel_elastic/themes/main/style/dark-colors.css
  skins/mel_elastic/themes/main/style/less/colors.less
  skins/mel_elastic/themes/main/style/less/dark-colors.less
Labels: enhancement

#120 0008724: Impossible d'inviter une personne en @ars.sante.fr
  plugins/mel/lib/drivers/mtes/mtes.php
Labels: enhancement

#119 0008757: Ajouter de l'auto complétion des tags
  plugins/mel_forum/js/lib/create_or_edit_post.js
  plugins/mel_forum/js/lib/forum.js
  plugins/mel_forum/mel_forum.php
  plugins/mel_forum/skins/mel_elastic/less/mel_forum.less
  plugins/mel_forum/skins/mel_elastic/mel_forum.css
  plugins/mel_forum/skins/mel_elastic/templates/create-post.html
  plugins/mel_forum/skins/mel_elastic/templates/forum.html
Labels: enhancement

#123 prettier - Application de prettier sur `create.js`
  plugins/roundrive/create.js
Labels: style code update

#124 0008466 - Pastille bleue sur le bouton créer s'affiche lorsqu'on choisi de créer un document
  plugins/roundrive/create.js
Labels: bug

#125 0008892 - Référence circulaire sur le BootstrapLoader.
  plugins/mel_metapage/js/lib/base_mel_object.js
  plugins/mel_metapage/js/lib/html/JsHtml/CustomAttributes/js_html_base_web_elements.js
  plugins/mel_metapage/js/lib/mel_object.js
Labels: bug

#126 0008850: Masquer le menu Double authentification dans les Courrielleurs
  plugins/mel_courrielleur/skins/courrielleur.css
  plugins/mel_courrielleur/skins/courrielleur.min.css
Labels: bug

#114 0008885 - probleme de multiples notifications lors de la publication
  plugins/mel_forum/js/lib/create_or_edit_post.js
  plugins/mel_forum/mel_forum.php
Labels: bug

#133 0008867 - La recherche de prochaines disponibilités communes devrait se baser sur le choix de la période
  plugins/mel_metapage/js/lib/calendar/event/parts/guestspart.free_busy.js
  plugins/mel_metapage/js/lib/calendar/event/parts/guestspart.js
Labels: bug
