Repository messagerie-melanie2/Roundcube-plugins-Mel, pull requests merged in 2025-05, with the labels that each got.

#199 0008949 - :bug: Les menu de gauche disparaissent après avoir ouvert une liste de diffusion
  plugins/annuaire/annuaire.php
  plugins/annuaire/js/lib/show.js
  plugins/mel_metapage/js/init/events.js
Labels: bug

#203 0008957 - 🐛 Affichage de l'arborescence de l'annuaire en mode clair : Changer le color des descriptions pour que ça s'affiche
  plugins/mel_metapage/skins/mel_elastic/annuaire_part.css
  plugins/mel_metapage/skins/mel_elastic/less/annuaire_part.less
Labels: bug

#204 recette - 0008958 - :bug: Ajouter les participants était toujours appelé
  plugins/mel_metapage/js/init/classes/addons/calendar_base.js
  plugins/mel_metapage/js/init/classes/addons/calendar_base.min.js
  plugins/mel_metapage/js/lib/calendar/event/parts/guestspart.js
  plugins/mel_workspace/js/lib/program/WorkspaceObject.js
  plugins/mel_workspace/js/lib/program/addons/calendar/calendar_additions.js
Labels: bug

#206 recette - 0008954 - :bento: Ajouter le lien MyASP dans la bibliothèque d'applications pour la branche ASP
  plugins/mel_useful_link/icon/organisation/partenaires/ASP/my-asp.png
Labels: asset

#207 recette - 8914 - :bento: - changement du logo
  plugins/mel_signatures/images/logotype/ASP.gif
  plugins/mel_signatures/images/logotype/ASP.png
Labels: asset

#209 0008967 - :bug: Création d'un event depuis l'edt n'attribut pas le nom en mode workspace lorsqu'on a le module agenda de la bali ouverte en parallèle
  plugins/bnum_agenda/bnum_agenda.php
  plugins/bnum_agenda/config.inc.php.dist
  plugins/bnum_agenda/js/lib/connectors.js
  plugins/mel_metapage/js/functions.js
  plugins/mel_metapage/js/lib/calendar/main.js
  plugins/mel_metapage/js/lib/helpers/bnum_connections/bnum_connections.js
Labels: bug

#211 0008403 - 🐛 Accessibilité des boutons Resynchronisation et Suppression d'un mobile
  plugins/mel_moncompte/localization/fr_FR.inc
  plugins/mel_moncompte/mobile.js
  plugins/mel_moncompte/statistiques/mobile.php
Labels: bug

#213 0007634 - :ambulance: Corrections des effets de bords du ticket #169
  plugins/mel/lib/drivers/mtes/mtes.php
  plugins/mel_contacts/lib/mel_contacts_mapping.php
Labels: bug

#217 prettier - 🎨 Application de prettier php sur mel_labels_sync.php
  plugins/mel_labels_sync/mel_labels_sync.php
Labels: style code update

#218 0008966 - 🐛 Création d'étiquette sans nom
  plugins/mel_labels_sync/mel_labels_sync.php
Labels: bug

#225 0008952 - :bug: Remplacer imap par storage
  plugins/mel_labels_sync/mel_labels_sync.php
  plugins/mel_metapage/mel_metapage.php
Labels: bug

#223 0009017 - :bug: Désactiver favikontoolkit
  plugins/mel_useful_link/js/lib/manager.js
Labels: bug

#224 0008988 - :sparkles: Le lien vers sympa pour les listes ont changés
  plugins/mel/lib/drivers/mtes/mtes.php
Labels: bug, enhancement

#226 0008918 - ✨ Rajouter une option calendly dans le générateur de signature
  plugins/bnum_agenda/bnum_agenda.php
  plugins/bnum_agenda/localization/fr_FR.inc
  plugins/mel_signatures/mel_signatures.php
Labels: enhancement

#215 0008955 - 🐛 - Annuaire: La saisie dans recherche est en display
  plugins/annuaire/annuaire.js
  plugins/mel_metapage/js/functions.js
  plugins/mel_workspace/js/lib/program/actions/page.workspace.js
  plugins/mel_workspace/js/params.js
Labels: bug
